# Generated by Django 3.0.5 on 2020-04-28 21:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalogName', models.CharField(max_length=100)),
                ('api', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('poster', models.URLField(default='', max_length=500)),
                ('content', models.TextField(default='')),
                ('publicationTime', models.DateTimeField(auto_now_add=True)),
                ('changeTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alterName', models.CharField(max_length=100)),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('viewCount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(default='В работе', max_length=50)),
                ('releaseDate', models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1970)])),
                ('genre', models.TextField(default='')),
                ('studio', models.CharField(default='', max_length=100)),
                ('image1', models.URLField(default='', max_length=500)),
                ('description', models.TextField(default='')),
                ('ageLimit', models.PositiveSmallIntegerField(default=16, validators=[django.core.validators.MaxValueValidator(18), django.core.validators.MinValueValidator(0)])),
                ('screen_1_1', models.URLField(default='', max_length=500)),
                ('screen_1_2', models.URLField(default='', max_length=500)),
                ('screen_1_3', models.URLField(default='', max_length=500)),
                ('screen_1_4', models.URLField(default='', max_length=500)),
                ('screen_1_5', models.URLField(default='', max_length=500)),
                ('catalogType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Catalog')),
            ],
        ),
    ]
