# Generated by Django 3.0.5 on 2020-04-29 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_account_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='screen_1_1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='screen_1_2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='screen_1_3',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='screen_1_4',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='screen_1_5',
            field=models.CharField(default='', max_length=500),
        ),
    ]
