# Generated by Django 3.0.5 on 2020-04-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200429_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='poster',
            field=models.CharField(default='', max_length=500),
        ),
    ]
